version: '2'

services:
  modifiedapp:
    build: .
    volumes:
      - ./webroot:/webroot
    ports:
      - '8123:80'
    env_file:
      - env
  modifieddb:
    image: mariadb:10.5
    env_file:
      - env
    volumes:
      - ./dbdata:/var/lib/mysql
